// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: agynio/api/identity/v1/identity.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_RegisterIdentity_FullMethodName      = "/agynio.api.identity.v1.IdentityService/RegisterIdentity"
	IdentityService_GetIdentityType_FullMethodName       = "/agynio.api.identity.v1.IdentityService/GetIdentityType"
	IdentityService_BatchGetIdentityTypes_FullMethodName = "/agynio.api.identity.v1.IdentityService/BatchGetIdentityTypes"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService provides the canonical registry of identity IDs and types.
type IdentityServiceClient interface {
	// RegisterIdentity stores a new identity ID and its type.
	// Returns ALREADY_EXISTS if the identity_id is already registered.
	RegisterIdentity(ctx context.Context, in *RegisterIdentityRequest, opts ...grpc.CallOption) (*RegisterIdentityResponse, error)
	// GetIdentityType returns the type for a single identity ID.
	// Returns NOT_FOUND if the identity_id is unknown.
	GetIdentityType(ctx context.Context, in *GetIdentityTypeRequest, opts ...grpc.CallOption) (*GetIdentityTypeResponse, error)
	// BatchGetIdentityTypes returns known identity types for the requested IDs.
	// Unknown identity IDs are omitted from the response.
	BatchGetIdentityTypes(ctx context.Context, in *BatchGetIdentityTypesRequest, opts ...grpc.CallOption) (*BatchGetIdentityTypesResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) RegisterIdentity(ctx context.Context, in *RegisterIdentityRequest, opts ...grpc.CallOption) (*RegisterIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterIdentityResponse)
	err := c.cc.Invoke(ctx, IdentityService_RegisterIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetIdentityType(ctx context.Context, in *GetIdentityTypeRequest, opts ...grpc.CallOption) (*GetIdentityTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdentityTypeResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetIdentityType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) BatchGetIdentityTypes(ctx context.Context, in *BatchGetIdentityTypesRequest, opts ...grpc.CallOption) (*BatchGetIdentityTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetIdentityTypesResponse)
	err := c.cc.Invoke(ctx, IdentityService_BatchGetIdentityTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations should embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService provides the canonical registry of identity IDs and types.
type IdentityServiceServer interface {
	// RegisterIdentity stores a new identity ID and its type.
	// Returns ALREADY_EXISTS if the identity_id is already registered.
	RegisterIdentity(context.Context, *RegisterIdentityRequest) (*RegisterIdentityResponse, error)
	// GetIdentityType returns the type for a single identity ID.
	// Returns NOT_FOUND if the identity_id is unknown.
	GetIdentityType(context.Context, *GetIdentityTypeRequest) (*GetIdentityTypeResponse, error)
	// BatchGetIdentityTypes returns known identity types for the requested IDs.
	// Unknown identity IDs are omitted from the response.
	BatchGetIdentityTypes(context.Context, *BatchGetIdentityTypesRequest) (*BatchGetIdentityTypesResponse, error)
}

// UnimplementedIdentityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) RegisterIdentity(context.Context, *RegisterIdentityRequest) (*RegisterIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterIdentity not implemented")
}
func (UnimplementedIdentityServiceServer) GetIdentityType(context.Context, *GetIdentityTypeRequest) (*GetIdentityTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentityType not implemented")
}
func (UnimplementedIdentityServiceServer) BatchGetIdentityTypes(context.Context, *BatchGetIdentityTypesRequest) (*BatchGetIdentityTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetIdentityTypes not implemented")
}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue() {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_RegisterIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RegisterIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RegisterIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RegisterIdentity(ctx, req.(*RegisterIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetIdentityType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetIdentityType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetIdentityType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetIdentityType(ctx, req.(*GetIdentityTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_BatchGetIdentityTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetIdentityTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).BatchGetIdentityTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_BatchGetIdentityTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).BatchGetIdentityTypes(ctx, req.(*BatchGetIdentityTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.identity.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterIdentity",
			Handler:    _IdentityService_RegisterIdentity_Handler,
		},
		{
			MethodName: "GetIdentityType",
			Handler:    _IdentityService_GetIdentityType_Handler,
		},
		{
			MethodName: "BatchGetIdentityTypes",
			Handler:    _IdentityService_BatchGetIdentityTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/identity/v1/identity.proto",
}
