// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/identity/v1/identity.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityType int32

const (
	IdentityType_IDENTITY_TYPE_UNSPECIFIED IdentityType = 0
	IdentityType_IDENTITY_TYPE_AGENT       IdentityType = 1
	IdentityType_IDENTITY_TYPE_RUNNER      IdentityType = 2
	IdentityType_IDENTITY_TYPE_CHANNEL     IdentityType = 3
	IdentityType_IDENTITY_TYPE_USER        IdentityType = 4
	IdentityType_IDENTITY_TYPE_APP         IdentityType = 5
)

// Enum value maps for IdentityType.
var (
	IdentityType_name = map[int32]string{
		0: "IDENTITY_TYPE_UNSPECIFIED",
		1: "IDENTITY_TYPE_AGENT",
		2: "IDENTITY_TYPE_RUNNER",
		3: "IDENTITY_TYPE_CHANNEL",
		4: "IDENTITY_TYPE_USER",
		5: "IDENTITY_TYPE_APP",
	}
	IdentityType_value = map[string]int32{
		"IDENTITY_TYPE_UNSPECIFIED": 0,
		"IDENTITY_TYPE_AGENT":       1,
		"IDENTITY_TYPE_RUNNER":      2,
		"IDENTITY_TYPE_CHANNEL":     3,
		"IDENTITY_TYPE_USER":        4,
		"IDENTITY_TYPE_APP":         5,
	}
)

func (x IdentityType) Enum() *IdentityType {
	p := new(IdentityType)
	*p = x
	return p
}

func (x IdentityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityType) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_identity_v1_identity_proto_enumTypes[0].Descriptor()
}

func (IdentityType) Type() protoreflect.EnumType {
	return &file_agynio_api_identity_v1_identity_proto_enumTypes[0]
}

func (x IdentityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityType.Descriptor instead.
func (IdentityType) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

type RegisterIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	IdentityType  IdentityType           `protobuf:"varint,2,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.identity.v1.IdentityType" json:"identity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterIdentityRequest) Reset() {
	*x = RegisterIdentityRequest{}
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIdentityRequest) ProtoMessage() {}

func (x *RegisterIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIdentityRequest.ProtoReflect.Descriptor instead.
func (*RegisterIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterIdentityRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *RegisterIdentityRequest) GetIdentityType() IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

type RegisterIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterIdentityResponse) Reset() {
	*x = RegisterIdentityResponse{}
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIdentityResponse) ProtoMessage() {}

func (x *RegisterIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIdentityResponse.ProtoReflect.Descriptor instead.
func (*RegisterIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

type GetIdentityTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityTypeRequest) Reset() {
	*x = GetIdentityTypeRequest{}
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityTypeRequest) ProtoMessage() {}

func (x *GetIdentityTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityTypeRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityTypeRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetIdentityTypeRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

type GetIdentityTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityType  IdentityType           `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.identity.v1.IdentityType" json:"identity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityTypeResponse) Reset() {
	*x = GetIdentityTypeResponse{}
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityTypeResponse) ProtoMessage() {}

func (x *GetIdentityTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityTypeResponse.ProtoReflect.Descriptor instead.
func (*GetIdentityTypeResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetIdentityTypeResponse) GetIdentityType() IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

type BatchGetIdentityTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityIds   []string               `protobuf:"bytes,1,rep,name=identity_ids,json=identityIds,proto3" json:"identity_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetIdentityTypesRequest) Reset() {
	*x = BatchGetIdentityTypesRequest{}
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetIdentityTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetIdentityTypesRequest) ProtoMessage() {}

func (x *BatchGetIdentityTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetIdentityTypesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetIdentityTypesRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetIdentityTypesRequest) GetIdentityIds() []string {
	if x != nil {
		return x.IdentityIds
	}
	return nil
}

type IdentityTypeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	IdentityType  IdentityType           `protobuf:"varint,2,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.identity.v1.IdentityType" json:"identity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityTypeEntry) Reset() {
	*x = IdentityTypeEntry{}
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityTypeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityTypeEntry) ProtoMessage() {}

func (x *IdentityTypeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityTypeEntry.ProtoReflect.Descriptor instead.
func (*IdentityTypeEntry) Descriptor() ([]byte, []int) {
	return file_agynio_api_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *IdentityTypeEntry) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *IdentityTypeEntry) GetIdentityType() IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

type BatchGetIdentityTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*IdentityTypeEntry   `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetIdentityTypesResponse) Reset() {
	*x = BatchGetIdentityTypesResponse{}
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetIdentityTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetIdentityTypesResponse) ProtoMessage() {}

func (x *BatchGetIdentityTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_identity_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetIdentityTypesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetIdentityTypesResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_identity_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetIdentityTypesResponse) GetEntries() []*IdentityTypeEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_agynio_api_identity_v1_identity_proto protoreflect.FileDescriptor

const file_agynio_api_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"%agynio/api/identity/v1/identity.proto\x12\x16agynio.api.identity.v1\"\x85\x01\n" +
	"\x17RegisterIdentityRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12I\n" +
	"\ridentity_type\x18\x02 \x01(\x0e2$.agynio.api.identity.v1.IdentityTypeR\fidentityType\"\x1a\n" +
	"\x18RegisterIdentityResponse\"9\n" +
	"\x16GetIdentityTypeRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\"d\n" +
	"\x17GetIdentityTypeResponse\x12I\n" +
	"\ridentity_type\x18\x01 \x01(\x0e2$.agynio.api.identity.v1.IdentityTypeR\fidentityType\"A\n" +
	"\x1cBatchGetIdentityTypesRequest\x12!\n" +
	"\fidentity_ids\x18\x01 \x03(\tR\videntityIds\"\x7f\n" +
	"\x11IdentityTypeEntry\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12I\n" +
	"\ridentity_type\x18\x02 \x01(\x0e2$.agynio.api.identity.v1.IdentityTypeR\fidentityType\"d\n" +
	"\x1dBatchGetIdentityTypesResponse\x12C\n" +
	"\aentries\x18\x01 \x03(\v2).agynio.api.identity.v1.IdentityTypeEntryR\aentries*\xaa\x01\n" +
	"\fIdentityType\x12\x1d\n" +
	"\x19IDENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13IDENTITY_TYPE_AGENT\x10\x01\x12\x18\n" +
	"\x14IDENTITY_TYPE_RUNNER\x10\x02\x12\x19\n" +
	"\x15IDENTITY_TYPE_CHANNEL\x10\x03\x12\x16\n" +
	"\x12IDENTITY_TYPE_USER\x10\x04\x12\x15\n" +
	"\x11IDENTITY_TYPE_APP\x10\x052\x83\x03\n" +
	"\x0fIdentityService\x12u\n" +
	"\x10RegisterIdentity\x12/.agynio.api.identity.v1.RegisterIdentityRequest\x1a0.agynio.api.identity.v1.RegisterIdentityResponse\x12r\n" +
	"\x0fGetIdentityType\x12..agynio.api.identity.v1.GetIdentityTypeRequest\x1a/.agynio.api.identity.v1.GetIdentityTypeResponse\x12\x84\x01\n" +
	"\x15BatchGetIdentityTypes\x124.agynio.api.identity.v1.BatchGetIdentityTypesRequest\x1a5.agynio.api.identity.v1.BatchGetIdentityTypesResponseB\xf3\x01\n" +
	"\x1acom.agynio.api.identity.v1B\rIdentityProtoP\x01ZKgithub.com/agynio/ziti-management/.gen/go/agynio/api/identity/v1;identityv1\xa2\x02\x03AAI\xaa\x02\x16Agynio.Api.Identity.V1\xca\x02\x16Agynio\\Api\\Identity\\V1\xe2\x02\"Agynio\\Api\\Identity\\V1\\GPBMetadata\xea\x02\x19Agynio::Api::Identity::V1b\x06proto3"

var (
	file_agynio_api_identity_v1_identity_proto_rawDescOnce sync.Once
	file_agynio_api_identity_v1_identity_proto_rawDescData []byte
)

func file_agynio_api_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_agynio_api_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_agynio_api_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_identity_v1_identity_proto_rawDesc), len(file_agynio_api_identity_v1_identity_proto_rawDesc)))
	})
	return file_agynio_api_identity_v1_identity_proto_rawDescData
}

var file_agynio_api_identity_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agynio_api_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agynio_api_identity_v1_identity_proto_goTypes = []any{
	(IdentityType)(0),                     // 0: agynio.api.identity.v1.IdentityType
	(*RegisterIdentityRequest)(nil),       // 1: agynio.api.identity.v1.RegisterIdentityRequest
	(*RegisterIdentityResponse)(nil),      // 2: agynio.api.identity.v1.RegisterIdentityResponse
	(*GetIdentityTypeRequest)(nil),        // 3: agynio.api.identity.v1.GetIdentityTypeRequest
	(*GetIdentityTypeResponse)(nil),       // 4: agynio.api.identity.v1.GetIdentityTypeResponse
	(*BatchGetIdentityTypesRequest)(nil),  // 5: agynio.api.identity.v1.BatchGetIdentityTypesRequest
	(*IdentityTypeEntry)(nil),             // 6: agynio.api.identity.v1.IdentityTypeEntry
	(*BatchGetIdentityTypesResponse)(nil), // 7: agynio.api.identity.v1.BatchGetIdentityTypesResponse
}
var file_agynio_api_identity_v1_identity_proto_depIdxs = []int32{
	0, // 0: agynio.api.identity.v1.RegisterIdentityRequest.identity_type:type_name -> agynio.api.identity.v1.IdentityType
	0, // 1: agynio.api.identity.v1.GetIdentityTypeResponse.identity_type:type_name -> agynio.api.identity.v1.IdentityType
	0, // 2: agynio.api.identity.v1.IdentityTypeEntry.identity_type:type_name -> agynio.api.identity.v1.IdentityType
	6, // 3: agynio.api.identity.v1.BatchGetIdentityTypesResponse.entries:type_name -> agynio.api.identity.v1.IdentityTypeEntry
	1, // 4: agynio.api.identity.v1.IdentityService.RegisterIdentity:input_type -> agynio.api.identity.v1.RegisterIdentityRequest
	3, // 5: agynio.api.identity.v1.IdentityService.GetIdentityType:input_type -> agynio.api.identity.v1.GetIdentityTypeRequest
	5, // 6: agynio.api.identity.v1.IdentityService.BatchGetIdentityTypes:input_type -> agynio.api.identity.v1.BatchGetIdentityTypesRequest
	2, // 7: agynio.api.identity.v1.IdentityService.RegisterIdentity:output_type -> agynio.api.identity.v1.RegisterIdentityResponse
	4, // 8: agynio.api.identity.v1.IdentityService.GetIdentityType:output_type -> agynio.api.identity.v1.GetIdentityTypeResponse
	7, // 9: agynio.api.identity.v1.IdentityService.BatchGetIdentityTypes:output_type -> agynio.api.identity.v1.BatchGetIdentityTypesResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agynio_api_identity_v1_identity_proto_init() }
func file_agynio_api_identity_v1_identity_proto_init() {
	if File_agynio_api_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_identity_v1_identity_proto_rawDesc), len(file_agynio_api_identity_v1_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_agynio_api_identity_v1_identity_proto_depIdxs,
		EnumInfos:         file_agynio_api_identity_v1_identity_proto_enumTypes,
		MessageInfos:      file_agynio_api_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_agynio_api_identity_v1_identity_proto = out.File
	file_agynio_api_identity_v1_identity_proto_goTypes = nil
	file_agynio_api_identity_v1_identity_proto_depIdxs = nil
}
