// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: agynio/api/ziti_management/v1/ziti_management.proto

package ziti_managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZitiManagementService_CreateAgentIdentity_FullMethodName    = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateAgentIdentity"
	ZitiManagementService_DeleteIdentity_FullMethodName         = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteIdentity"
	ZitiManagementService_ListManagedIdentities_FullMethodName  = "/agynio.api.ziti_management.v1.ZitiManagementService/ListManagedIdentities"
	ZitiManagementService_ResolveIdentity_FullMethodName        = "/agynio.api.ziti_management.v1.ZitiManagementService/ResolveIdentity"
	ZitiManagementService_RequestServiceIdentity_FullMethodName = "/agynio.api.ziti_management.v1.ZitiManagementService/RequestServiceIdentity"
	ZitiManagementService_ExtendIdentityLease_FullMethodName    = "/agynio.api.ziti_management.v1.ZitiManagementService/ExtendIdentityLease"
)

// ZitiManagementServiceClient is the client API for ZitiManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZitiManagementServiceClient interface {
	// Orchestrator -> create OpenZiti identity for an agent, return enrollment JWT.
	CreateAgentIdentity(ctx context.Context, in *CreateAgentIdentityRequest, opts ...grpc.CallOption) (*CreateAgentIdentityResponse, error)
	// Orchestrator -> delete OpenZiti identity and its platform mapping.
	DeleteIdentity(ctx context.Context, in *DeleteIdentityRequest, opts ...grpc.CallOption) (*DeleteIdentityResponse, error)
	// Orchestrator -> list all platform-managed identities (orphan reconciliation).
	ListManagedIdentities(ctx context.Context, in *ListManagedIdentitiesRequest, opts ...grpc.CallOption) (*ListManagedIdentitiesResponse, error)
	// Gateway -> map OpenZiti identity ID to platform identity (hot path).
	ResolveIdentity(ctx context.Context, in *ResolveIdentityRequest, opts ...grpc.CallOption) (*ResolveIdentityResponse, error)
	// Infrastructure services (Gateway, Orchestrator, Runner) -> request an enrolled
	// OpenZiti identity for the calling service. Ziti Management creates the identity
	// on the Controller, enrolls it (generates key pair, submits CSR, receives cert),
	// and returns the enrolled identity to the caller.
	RequestServiceIdentity(ctx context.Context, in *RequestServiceIdentityRequest, opts ...grpc.CallOption) (*RequestServiceIdentityResponse, error)
	// Infrastructure services -> extend the lease on a service identity.
	// Called periodically by the service to prevent GC from deleting the identity.
	ExtendIdentityLease(ctx context.Context, in *ExtendIdentityLeaseRequest, opts ...grpc.CallOption) (*ExtendIdentityLeaseResponse, error)
}

type zitiManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZitiManagementServiceClient(cc grpc.ClientConnInterface) ZitiManagementServiceClient {
	return &zitiManagementServiceClient{cc}
}

func (c *zitiManagementServiceClient) CreateAgentIdentity(ctx context.Context, in *CreateAgentIdentityRequest, opts ...grpc.CallOption) (*CreateAgentIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_CreateAgentIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) DeleteIdentity(ctx context.Context, in *DeleteIdentityRequest, opts ...grpc.CallOption) (*DeleteIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_DeleteIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ListManagedIdentities(ctx context.Context, in *ListManagedIdentitiesRequest, opts ...grpc.CallOption) (*ListManagedIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManagedIdentitiesResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ListManagedIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ResolveIdentity(ctx context.Context, in *ResolveIdentityRequest, opts ...grpc.CallOption) (*ResolveIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ResolveIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) RequestServiceIdentity(ctx context.Context, in *RequestServiceIdentityRequest, opts ...grpc.CallOption) (*RequestServiceIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestServiceIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_RequestServiceIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ExtendIdentityLease(ctx context.Context, in *ExtendIdentityLeaseRequest, opts ...grpc.CallOption) (*ExtendIdentityLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendIdentityLeaseResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ExtendIdentityLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZitiManagementServiceServer is the server API for ZitiManagementService service.
// All implementations should embed UnimplementedZitiManagementServiceServer
// for forward compatibility.
type ZitiManagementServiceServer interface {
	// Orchestrator -> create OpenZiti identity for an agent, return enrollment JWT.
	CreateAgentIdentity(context.Context, *CreateAgentIdentityRequest) (*CreateAgentIdentityResponse, error)
	// Orchestrator -> delete OpenZiti identity and its platform mapping.
	DeleteIdentity(context.Context, *DeleteIdentityRequest) (*DeleteIdentityResponse, error)
	// Orchestrator -> list all platform-managed identities (orphan reconciliation).
	ListManagedIdentities(context.Context, *ListManagedIdentitiesRequest) (*ListManagedIdentitiesResponse, error)
	// Gateway -> map OpenZiti identity ID to platform identity (hot path).
	ResolveIdentity(context.Context, *ResolveIdentityRequest) (*ResolveIdentityResponse, error)
	// Infrastructure services (Gateway, Orchestrator, Runner) -> request an enrolled
	// OpenZiti identity for the calling service. Ziti Management creates the identity
	// on the Controller, enrolls it (generates key pair, submits CSR, receives cert),
	// and returns the enrolled identity to the caller.
	RequestServiceIdentity(context.Context, *RequestServiceIdentityRequest) (*RequestServiceIdentityResponse, error)
	// Infrastructure services -> extend the lease on a service identity.
	// Called periodically by the service to prevent GC from deleting the identity.
	ExtendIdentityLease(context.Context, *ExtendIdentityLeaseRequest) (*ExtendIdentityLeaseResponse, error)
}

// UnimplementedZitiManagementServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZitiManagementServiceServer struct{}

func (UnimplementedZitiManagementServiceServer) CreateAgentIdentity(context.Context, *CreateAgentIdentityRequest) (*CreateAgentIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgentIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) DeleteIdentity(context.Context, *DeleteIdentityRequest) (*DeleteIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) ListManagedIdentities(context.Context, *ListManagedIdentitiesRequest) (*ListManagedIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManagedIdentities not implemented")
}
func (UnimplementedZitiManagementServiceServer) ResolveIdentity(context.Context, *ResolveIdentityRequest) (*ResolveIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) RequestServiceIdentity(context.Context, *RequestServiceIdentityRequest) (*RequestServiceIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestServiceIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) ExtendIdentityLease(context.Context, *ExtendIdentityLeaseRequest) (*ExtendIdentityLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendIdentityLease not implemented")
}
func (UnimplementedZitiManagementServiceServer) testEmbeddedByValue() {}

// UnsafeZitiManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZitiManagementServiceServer will
// result in compilation errors.
type UnsafeZitiManagementServiceServer interface {
	mustEmbedUnimplementedZitiManagementServiceServer()
}

func RegisterZitiManagementServiceServer(s grpc.ServiceRegistrar, srv ZitiManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedZitiManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZitiManagementService_ServiceDesc, srv)
}

func _ZitiManagementService_CreateAgentIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).CreateAgentIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_CreateAgentIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).CreateAgentIdentity(ctx, req.(*CreateAgentIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_DeleteIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).DeleteIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_DeleteIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).DeleteIdentity(ctx, req.(*DeleteIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ListManagedIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManagedIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ListManagedIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ListManagedIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ListManagedIdentities(ctx, req.(*ListManagedIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ResolveIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ResolveIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ResolveIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ResolveIdentity(ctx, req.(*ResolveIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_RequestServiceIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestServiceIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).RequestServiceIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_RequestServiceIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).RequestServiceIdentity(ctx, req.(*RequestServiceIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ExtendIdentityLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendIdentityLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ExtendIdentityLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ExtendIdentityLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ExtendIdentityLease(ctx, req.(*ExtendIdentityLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZitiManagementService_ServiceDesc is the grpc.ServiceDesc for ZitiManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZitiManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.ziti_management.v1.ZitiManagementService",
	HandlerType: (*ZitiManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgentIdentity",
			Handler:    _ZitiManagementService_CreateAgentIdentity_Handler,
		},
		{
			MethodName: "DeleteIdentity",
			Handler:    _ZitiManagementService_DeleteIdentity_Handler,
		},
		{
			MethodName: "ListManagedIdentities",
			Handler:    _ZitiManagementService_ListManagedIdentities_Handler,
		},
		{
			MethodName: "ResolveIdentity",
			Handler:    _ZitiManagementService_ResolveIdentity_Handler,
		},
		{
			MethodName: "RequestServiceIdentity",
			Handler:    _ZitiManagementService_RequestServiceIdentity_Handler,
		},
		{
			MethodName: "ExtendIdentityLease",
			Handler:    _ZitiManagementService_ExtendIdentityLease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/ziti_management/v1/ziti_management.proto",
}
