// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/ziti_management/v1/ziti_management.proto

package ziti_managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityType int32

const (
	IdentityType_IDENTITY_TYPE_UNSPECIFIED IdentityType = 0
	IdentityType_IDENTITY_TYPE_AGENT       IdentityType = 1
	IdentityType_IDENTITY_TYPE_RUNNER      IdentityType = 2
	IdentityType_IDENTITY_TYPE_CHANNEL     IdentityType = 3
)

// Enum value maps for IdentityType.
var (
	IdentityType_name = map[int32]string{
		0: "IDENTITY_TYPE_UNSPECIFIED",
		1: "IDENTITY_TYPE_AGENT",
		2: "IDENTITY_TYPE_RUNNER",
		3: "IDENTITY_TYPE_CHANNEL",
	}
	IdentityType_value = map[string]int32{
		"IDENTITY_TYPE_UNSPECIFIED": 0,
		"IDENTITY_TYPE_AGENT":       1,
		"IDENTITY_TYPE_RUNNER":      2,
		"IDENTITY_TYPE_CHANNEL":     3,
	}
)

func (x IdentityType) Enum() *IdentityType {
	p := new(IdentityType)
	*p = x
	return p
}

func (x IdentityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityType) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes[0].Descriptor()
}

func (IdentityType) Type() protoreflect.EnumType {
	return &file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes[0]
}

func (x IdentityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityType.Descriptor instead.
func (IdentityType) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{0}
}

type ManagedIdentity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	IdentityId     string                 `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	IdentityType   IdentityType           `protobuf:"varint,3,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.ziti_management.v1.IdentityType" json:"identity_type,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ManagedIdentity) Reset() {
	*x = ManagedIdentity{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedIdentity) ProtoMessage() {}

func (x *ManagedIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedIdentity.ProtoReflect.Descriptor instead.
func (*ManagedIdentity) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{0}
}

func (x *ManagedIdentity) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *ManagedIdentity) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *ManagedIdentity) GetIdentityType() IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

func (x *ManagedIdentity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAgentIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentIdentityRequest) Reset() {
	*x = CreateAgentIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentIdentityRequest) ProtoMessage() {}

func (x *CreateAgentIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentIdentityRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentIdentityRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type CreateAgentIdentityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	EnrollmentJwt  string                 `protobuf:"bytes,2,opt,name=enrollment_jwt,json=enrollmentJwt,proto3" json:"enrollment_jwt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAgentIdentityResponse) Reset() {
	*x = CreateAgentIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentIdentityResponse) ProtoMessage() {}

func (x *CreateAgentIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentIdentityResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAgentIdentityResponse) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *CreateAgentIdentityResponse) GetEnrollmentJwt() string {
	if x != nil {
		return x.EnrollmentJwt
	}
	return ""
}

type DeleteIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteIdentityRequest) Reset() {
	*x = DeleteIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIdentityRequest) ProtoMessage() {}

func (x *DeleteIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIdentityRequest.ProtoReflect.Descriptor instead.
func (*DeleteIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteIdentityRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type DeleteIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIdentityResponse) Reset() {
	*x = DeleteIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIdentityResponse) ProtoMessage() {}

func (x *DeleteIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIdentityResponse.ProtoReflect.Descriptor instead.
func (*DeleteIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{4}
}

type ListManagedIdentitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityType  IdentityType           `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.ziti_management.v1.IdentityType" json:"identity_type,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedIdentitiesRequest) Reset() {
	*x = ListManagedIdentitiesRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedIdentitiesRequest) ProtoMessage() {}

func (x *ListManagedIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*ListManagedIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{5}
}

func (x *ListManagedIdentitiesRequest) GetIdentityType() IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

func (x *ListManagedIdentitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListManagedIdentitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListManagedIdentitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*ManagedIdentity     `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedIdentitiesResponse) Reset() {
	*x = ListManagedIdentitiesResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedIdentitiesResponse) ProtoMessage() {}

func (x *ListManagedIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListManagedIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{6}
}

func (x *ListManagedIdentitiesResponse) GetIdentities() []*ManagedIdentity {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *ListManagedIdentitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ResolveIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveIdentityRequest) Reset() {
	*x = ResolveIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityRequest) ProtoMessage() {}

func (x *ResolveIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityRequest.ProtoReflect.Descriptor instead.
func (*ResolveIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveIdentityRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type ResolveIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	IdentityType  IdentityType           `protobuf:"varint,2,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.ziti_management.v1.IdentityType" json:"identity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdentityResponse) Reset() {
	*x = ResolveIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityResponse) ProtoMessage() {}

func (x *ResolveIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityResponse.ProtoReflect.Descriptor instead.
func (*ResolveIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveIdentityResponse) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *ResolveIdentityResponse) GetIdentityType() IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

var File_agynio_api_ziti_management_v1_ziti_management_proto protoreflect.FileDescriptor

const file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc = "" +
	"\n" +
	"3agynio/api/ziti_management/v1/ziti_management.proto\x12\x1dagynio.api.ziti_management.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n" +
	"\x0fManagedIdentity\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12P\n" +
	"\ridentity_type\x18\x03 \x01(\x0e2+.agynio.api.ziti_management.v1.IdentityTypeR\fidentityType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"7\n" +
	"\x1aCreateAgentIdentityRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"n\n" +
	"\x1bCreateAgentIdentityResponse\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12%\n" +
	"\x0eenrollment_jwt\x18\x02 \x01(\tR\renrollmentJwt\"A\n" +
	"\x15DeleteIdentityRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\"\x18\n" +
	"\x16DeleteIdentityResponse\"\xac\x01\n" +
	"\x1cListManagedIdentitiesRequest\x12P\n" +
	"\ridentity_type\x18\x01 \x01(\x0e2+.agynio.api.ziti_management.v1.IdentityTypeR\fidentityType\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x97\x01\n" +
	"\x1dListManagedIdentitiesResponse\x12N\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2..agynio.api.ziti_management.v1.ManagedIdentityR\n" +
	"identities\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"B\n" +
	"\x16ResolveIdentityRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\"\x8c\x01\n" +
	"\x17ResolveIdentityResponse\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12P\n" +
	"\ridentity_type\x18\x02 \x01(\x0e2+.agynio.api.ziti_management.v1.IdentityTypeR\fidentityType*{\n" +
	"\fIdentityType\x12\x1d\n" +
	"\x19IDENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13IDENTITY_TYPE_AGENT\x10\x01\x12\x18\n" +
	"\x14IDENTITY_TYPE_RUNNER\x10\x02\x12\x19\n" +
	"\x15IDENTITY_TYPE_CHANNEL\x10\x032\xbd\x04\n" +
	"\x15ZitiManagementService\x12\x8c\x01\n" +
	"\x13CreateAgentIdentity\x129.agynio.api.ziti_management.v1.CreateAgentIdentityRequest\x1a:.agynio.api.ziti_management.v1.CreateAgentIdentityResponse\x12}\n" +
	"\x0eDeleteIdentity\x124.agynio.api.ziti_management.v1.DeleteIdentityRequest\x1a5.agynio.api.ziti_management.v1.DeleteIdentityResponse\x12\x92\x01\n" +
	"\x15ListManagedIdentities\x12;.agynio.api.ziti_management.v1.ListManagedIdentitiesRequest\x1a<.agynio.api.ziti_management.v1.ListManagedIdentitiesResponse\x12\x80\x01\n" +
	"\x0fResolveIdentity\x125.agynio.api.ziti_management.v1.ResolveIdentityRequest\x1a6.agynio.api.ziti_management.v1.ResolveIdentityResponseB\xa6\x02\n" +
	"!com.agynio.api.ziti_management.v1B\x13ZitiManagementProtoP\x01ZYgithub.com/agynio/ziti-management/.gen/go/agynio/api/ziti_management/v1;ziti_managementv1\xa2\x02\x03AAZ\xaa\x02\x1cAgynio.Api.ZitiManagement.V1\xca\x02\x1cAgynio\\Api\\ZitiManagement\\V1\xe2\x02(Agynio\\Api\\ZitiManagement\\V1\\GPBMetadata\xea\x02\x1fAgynio::Api::ZitiManagement::V1b\x06proto3"

var (
	file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescOnce sync.Once
	file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescData []byte
)

func file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP() []byte {
	file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescOnce.Do(func() {
		file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc), len(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc)))
	})
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescData
}

var file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_agynio_api_ziti_management_v1_ziti_management_proto_goTypes = []any{
	(IdentityType)(0),                     // 0: agynio.api.ziti_management.v1.IdentityType
	(*ManagedIdentity)(nil),               // 1: agynio.api.ziti_management.v1.ManagedIdentity
	(*CreateAgentIdentityRequest)(nil),    // 2: agynio.api.ziti_management.v1.CreateAgentIdentityRequest
	(*CreateAgentIdentityResponse)(nil),   // 3: agynio.api.ziti_management.v1.CreateAgentIdentityResponse
	(*DeleteIdentityRequest)(nil),         // 4: agynio.api.ziti_management.v1.DeleteIdentityRequest
	(*DeleteIdentityResponse)(nil),        // 5: agynio.api.ziti_management.v1.DeleteIdentityResponse
	(*ListManagedIdentitiesRequest)(nil),  // 6: agynio.api.ziti_management.v1.ListManagedIdentitiesRequest
	(*ListManagedIdentitiesResponse)(nil), // 7: agynio.api.ziti_management.v1.ListManagedIdentitiesResponse
	(*ResolveIdentityRequest)(nil),        // 8: agynio.api.ziti_management.v1.ResolveIdentityRequest
	(*ResolveIdentityResponse)(nil),       // 9: agynio.api.ziti_management.v1.ResolveIdentityResponse
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
}
var file_agynio_api_ziti_management_v1_ziti_management_proto_depIdxs = []int32{
	0,  // 0: agynio.api.ziti_management.v1.ManagedIdentity.identity_type:type_name -> agynio.api.ziti_management.v1.IdentityType
	10, // 1: agynio.api.ziti_management.v1.ManagedIdentity.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: agynio.api.ziti_management.v1.ListManagedIdentitiesRequest.identity_type:type_name -> agynio.api.ziti_management.v1.IdentityType
	1,  // 3: agynio.api.ziti_management.v1.ListManagedIdentitiesResponse.identities:type_name -> agynio.api.ziti_management.v1.ManagedIdentity
	0,  // 4: agynio.api.ziti_management.v1.ResolveIdentityResponse.identity_type:type_name -> agynio.api.ziti_management.v1.IdentityType
	2,  // 5: agynio.api.ziti_management.v1.ZitiManagementService.CreateAgentIdentity:input_type -> agynio.api.ziti_management.v1.CreateAgentIdentityRequest
	4,  // 6: agynio.api.ziti_management.v1.ZitiManagementService.DeleteIdentity:input_type -> agynio.api.ziti_management.v1.DeleteIdentityRequest
	6,  // 7: agynio.api.ziti_management.v1.ZitiManagementService.ListManagedIdentities:input_type -> agynio.api.ziti_management.v1.ListManagedIdentitiesRequest
	8,  // 8: agynio.api.ziti_management.v1.ZitiManagementService.ResolveIdentity:input_type -> agynio.api.ziti_management.v1.ResolveIdentityRequest
	3,  // 9: agynio.api.ziti_management.v1.ZitiManagementService.CreateAgentIdentity:output_type -> agynio.api.ziti_management.v1.CreateAgentIdentityResponse
	5,  // 10: agynio.api.ziti_management.v1.ZitiManagementService.DeleteIdentity:output_type -> agynio.api.ziti_management.v1.DeleteIdentityResponse
	7,  // 11: agynio.api.ziti_management.v1.ZitiManagementService.ListManagedIdentities:output_type -> agynio.api.ziti_management.v1.ListManagedIdentitiesResponse
	9,  // 12: agynio.api.ziti_management.v1.ZitiManagementService.ResolveIdentity:output_type -> agynio.api.ziti_management.v1.ResolveIdentityResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_agynio_api_ziti_management_v1_ziti_management_proto_init() }
func file_agynio_api_ziti_management_v1_ziti_management_proto_init() {
	if File_agynio_api_ziti_management_v1_ziti_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc), len(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_ziti_management_v1_ziti_management_proto_goTypes,
		DependencyIndexes: file_agynio_api_ziti_management_v1_ziti_management_proto_depIdxs,
		EnumInfos:         file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes,
		MessageInfos:      file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes,
	}.Build()
	File_agynio_api_ziti_management_v1_ziti_management_proto = out.File
	file_agynio_api_ziti_management_v1_ziti_management_proto_goTypes = nil
	file_agynio_api_ziti_management_v1_ziti_management_proto_depIdxs = nil
}
