// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/ziti_management/v1/ziti_management.proto

package ziti_managementv1

import (
	v1 "github.com/agynio/ziti-management/.gen/go/agynio/api/identity/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNSPECIFIED  ServiceType = 0
	ServiceType_SERVICE_TYPE_GATEWAY      ServiceType = 1
	ServiceType_SERVICE_TYPE_ORCHESTRATOR ServiceType = 2
	ServiceType_SERVICE_TYPE_RUNNER       ServiceType = 3
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE_TYPE_GATEWAY",
		2: "SERVICE_TYPE_ORCHESTRATOR",
		3: "SERVICE_TYPE_RUNNER",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED":  0,
		"SERVICE_TYPE_GATEWAY":      1,
		"SERVICE_TYPE_ORCHESTRATOR": 2,
		"SERVICE_TYPE_RUNNER":       3,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{0}
}

type ManagedIdentity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	IdentityId     string                 `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	IdentityType   v1.IdentityType        `protobuf:"varint,3,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.identity.v1.IdentityType" json:"identity_type,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ManagedIdentity) Reset() {
	*x = ManagedIdentity{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedIdentity) ProtoMessage() {}

func (x *ManagedIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedIdentity.ProtoReflect.Descriptor instead.
func (*ManagedIdentity) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{0}
}

func (x *ManagedIdentity) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *ManagedIdentity) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *ManagedIdentity) GetIdentityType() v1.IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return v1.IdentityType(0)
}

func (x *ManagedIdentity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAgentIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentIdentityRequest) Reset() {
	*x = CreateAgentIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentIdentityRequest) ProtoMessage() {}

func (x *CreateAgentIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentIdentityRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentIdentityRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type CreateAgentIdentityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	EnrollmentJwt  string                 `protobuf:"bytes,2,opt,name=enrollment_jwt,json=enrollmentJwt,proto3" json:"enrollment_jwt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAgentIdentityResponse) Reset() {
	*x = CreateAgentIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentIdentityResponse) ProtoMessage() {}

func (x *CreateAgentIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentIdentityResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAgentIdentityResponse) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *CreateAgentIdentityResponse) GetEnrollmentJwt() string {
	if x != nil {
		return x.EnrollmentJwt
	}
	return ""
}

// Request to create an OpenZiti identity and service for an app.
type CreateAppIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppIdentityRequest) Reset() {
	*x = CreateAppIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppIdentityRequest) ProtoMessage() {}

func (x *CreateAppIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppIdentityRequest.ProtoReflect.Descriptor instead.
func (*CreateAppIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAppIdentityRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *CreateAppIdentityRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// Response with enrolled OpenZiti credentials for an app identity.
type CreateAppIdentityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	IdentityJson   []byte                 `protobuf:"bytes,2,opt,name=identity_json,json=identityJson,proto3" json:"identity_json,omitempty"`
	ZitiServiceId  string                 `protobuf:"bytes,3,opt,name=ziti_service_id,json=zitiServiceId,proto3" json:"ziti_service_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAppIdentityResponse) Reset() {
	*x = CreateAppIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppIdentityResponse) ProtoMessage() {}

func (x *CreateAppIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppIdentityResponse.ProtoReflect.Descriptor instead.
func (*CreateAppIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAppIdentityResponse) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *CreateAppIdentityResponse) GetIdentityJson() []byte {
	if x != nil {
		return x.IdentityJson
	}
	return nil
}

func (x *CreateAppIdentityResponse) GetZitiServiceId() string {
	if x != nil {
		return x.ZitiServiceId
	}
	return ""
}

// Request to delete an app's OpenZiti identity and service.
type DeleteAppIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	ZitiServiceId  string                 `protobuf:"bytes,2,opt,name=ziti_service_id,json=zitiServiceId,proto3" json:"ziti_service_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteAppIdentityRequest) Reset() {
	*x = DeleteAppIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppIdentityRequest) ProtoMessage() {}

func (x *DeleteAppIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppIdentityRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAppIdentityRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *DeleteAppIdentityRequest) GetZitiServiceId() string {
	if x != nil {
		return x.ZitiServiceId
	}
	return ""
}

// Response after deleting an app's OpenZiti identity.
type DeleteAppIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppIdentityResponse) Reset() {
	*x = DeleteAppIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppIdentityResponse) ProtoMessage() {}

func (x *DeleteAppIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppIdentityResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{6}
}

type DeleteIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteIdentityRequest) Reset() {
	*x = DeleteIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIdentityRequest) ProtoMessage() {}

func (x *DeleteIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIdentityRequest.ProtoReflect.Descriptor instead.
func (*DeleteIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteIdentityRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type DeleteIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIdentityResponse) Reset() {
	*x = DeleteIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIdentityResponse) ProtoMessage() {}

func (x *DeleteIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIdentityResponse.ProtoReflect.Descriptor instead.
func (*DeleteIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{8}
}

type ListManagedIdentitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityType  v1.IdentityType        `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.identity.v1.IdentityType" json:"identity_type,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedIdentitiesRequest) Reset() {
	*x = ListManagedIdentitiesRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedIdentitiesRequest) ProtoMessage() {}

func (x *ListManagedIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*ListManagedIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{9}
}

func (x *ListManagedIdentitiesRequest) GetIdentityType() v1.IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return v1.IdentityType(0)
}

func (x *ListManagedIdentitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListManagedIdentitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListManagedIdentitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*ManagedIdentity     `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedIdentitiesResponse) Reset() {
	*x = ListManagedIdentitiesResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedIdentitiesResponse) ProtoMessage() {}

func (x *ListManagedIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListManagedIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{10}
}

func (x *ListManagedIdentitiesResponse) GetIdentities() []*ManagedIdentity {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *ListManagedIdentitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ResolveIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveIdentityRequest) Reset() {
	*x = ResolveIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityRequest) ProtoMessage() {}

func (x *ResolveIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityRequest.ProtoReflect.Descriptor instead.
func (*ResolveIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveIdentityRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type ResolveIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	IdentityType  v1.IdentityType        `protobuf:"varint,2,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.identity.v1.IdentityType" json:"identity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdentityResponse) Reset() {
	*x = ResolveIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityResponse) ProtoMessage() {}

func (x *ResolveIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityResponse.ProtoReflect.Descriptor instead.
func (*ResolveIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveIdentityResponse) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *ResolveIdentityResponse) GetIdentityType() v1.IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return v1.IdentityType(0)
}

type RequestServiceIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which infrastructure service is requesting the identity.
	ServiceType   ServiceType `protobuf:"varint,1,opt,name=service_type,json=serviceType,proto3,enum=agynio.api.ziti_management.v1.ServiceType" json:"service_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestServiceIdentityRequest) Reset() {
	*x = RequestServiceIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestServiceIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestServiceIdentityRequest) ProtoMessage() {}

func (x *RequestServiceIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestServiceIdentityRequest.ProtoReflect.Descriptor instead.
func (*RequestServiceIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{13}
}

func (x *RequestServiceIdentityRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

type RequestServiceIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti identity ID (for lease extension and cleanup).
	ZitiIdentityId string `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	// The full enrolled identity JSON (contains cert, key, CA, controller URL).
	// The caller writes this to ephemeral disk and loads it via the OpenZiti SDK.
	IdentityJson  []byte `protobuf:"bytes,2,opt,name=identity_json,json=identityJson,proto3" json:"identity_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestServiceIdentityResponse) Reset() {
	*x = RequestServiceIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestServiceIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestServiceIdentityResponse) ProtoMessage() {}

func (x *RequestServiceIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestServiceIdentityResponse.ProtoReflect.Descriptor instead.
func (*RequestServiceIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{14}
}

func (x *RequestServiceIdentityResponse) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *RequestServiceIdentityResponse) GetIdentityJson() []byte {
	if x != nil {
		return x.IdentityJson
	}
	return nil
}

type ExtendIdentityLeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti identity ID whose lease should be extended.
	ZitiIdentityId string `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtendIdentityLeaseRequest) Reset() {
	*x = ExtendIdentityLeaseRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendIdentityLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendIdentityLeaseRequest) ProtoMessage() {}

func (x *ExtendIdentityLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendIdentityLeaseRequest.ProtoReflect.Descriptor instead.
func (*ExtendIdentityLeaseRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{15}
}

func (x *ExtendIdentityLeaseRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type ExtendIdentityLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendIdentityLeaseResponse) Reset() {
	*x = ExtendIdentityLeaseResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendIdentityLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendIdentityLeaseResponse) ProtoMessage() {}

func (x *ExtendIdentityLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendIdentityLeaseResponse.ProtoReflect.Descriptor instead.
func (*ExtendIdentityLeaseResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{16}
}

var File_agynio_api_ziti_management_v1_ziti_management_proto protoreflect.FileDescriptor

const file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc = "" +
	"\n" +
	"3agynio/api/ziti_management/v1/ziti_management.proto\x12\x1dagynio.api.ziti_management.v1\x1a%agynio/api/identity/v1/identity.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\x0fManagedIdentity\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12I\n" +
	"\ridentity_type\x18\x03 \x01(\x0e2$.agynio.api.identity.v1.IdentityTypeR\fidentityType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"7\n" +
	"\x1aCreateAgentIdentityRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"n\n" +
	"\x1bCreateAgentIdentityResponse\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12%\n" +
	"\x0eenrollment_jwt\x18\x02 \x01(\tR\renrollmentJwt\"O\n" +
	"\x18CreateAppIdentityRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"\x92\x01\n" +
	"\x19CreateAppIdentityResponse\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12#\n" +
	"\ridentity_json\x18\x02 \x01(\fR\fidentityJson\x12&\n" +
	"\x0fziti_service_id\x18\x03 \x01(\tR\rzitiServiceId\"l\n" +
	"\x18DeleteAppIdentityRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12&\n" +
	"\x0fziti_service_id\x18\x02 \x01(\tR\rzitiServiceId\"\x1b\n" +
	"\x19DeleteAppIdentityResponse\"A\n" +
	"\x15DeleteIdentityRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\"\x18\n" +
	"\x16DeleteIdentityResponse\"\xa5\x01\n" +
	"\x1cListManagedIdentitiesRequest\x12I\n" +
	"\ridentity_type\x18\x01 \x01(\x0e2$.agynio.api.identity.v1.IdentityTypeR\fidentityType\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x97\x01\n" +
	"\x1dListManagedIdentitiesResponse\x12N\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2..agynio.api.ziti_management.v1.ManagedIdentityR\n" +
	"identities\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"B\n" +
	"\x16ResolveIdentityRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\"\x85\x01\n" +
	"\x17ResolveIdentityResponse\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12I\n" +
	"\ridentity_type\x18\x02 \x01(\x0e2$.agynio.api.identity.v1.IdentityTypeR\fidentityType\"n\n" +
	"\x1dRequestServiceIdentityRequest\x12M\n" +
	"\fservice_type\x18\x01 \x01(\x0e2*.agynio.api.ziti_management.v1.ServiceTypeR\vserviceType\"o\n" +
	"\x1eRequestServiceIdentityResponse\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12#\n" +
	"\ridentity_json\x18\x02 \x01(\fR\fidentityJson\"F\n" +
	"\x1aExtendIdentityLeaseRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\"\x1d\n" +
	"\x1bExtendIdentityLeaseResponse*}\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SERVICE_TYPE_GATEWAY\x10\x01\x12\x1d\n" +
	"\x19SERVICE_TYPE_ORCHESTRATOR\x10\x02\x12\x17\n" +
	"\x13SERVICE_TYPE_RUNNER\x10\x032\xf6\b\n" +
	"\x15ZitiManagementService\x12\x8c\x01\n" +
	"\x13CreateAgentIdentity\x129.agynio.api.ziti_management.v1.CreateAgentIdentityRequest\x1a:.agynio.api.ziti_management.v1.CreateAgentIdentityResponse\x12\x86\x01\n" +
	"\x11CreateAppIdentity\x127.agynio.api.ziti_management.v1.CreateAppIdentityRequest\x1a8.agynio.api.ziti_management.v1.CreateAppIdentityResponse\x12}\n" +
	"\x0eDeleteIdentity\x124.agynio.api.ziti_management.v1.DeleteIdentityRequest\x1a5.agynio.api.ziti_management.v1.DeleteIdentityResponse\x12\x86\x01\n" +
	"\x11DeleteAppIdentity\x127.agynio.api.ziti_management.v1.DeleteAppIdentityRequest\x1a8.agynio.api.ziti_management.v1.DeleteAppIdentityResponse\x12\x92\x01\n" +
	"\x15ListManagedIdentities\x12;.agynio.api.ziti_management.v1.ListManagedIdentitiesRequest\x1a<.agynio.api.ziti_management.v1.ListManagedIdentitiesResponse\x12\x80\x01\n" +
	"\x0fResolveIdentity\x125.agynio.api.ziti_management.v1.ResolveIdentityRequest\x1a6.agynio.api.ziti_management.v1.ResolveIdentityResponse\x12\x95\x01\n" +
	"\x16RequestServiceIdentity\x12<.agynio.api.ziti_management.v1.RequestServiceIdentityRequest\x1a=.agynio.api.ziti_management.v1.RequestServiceIdentityResponse\x12\x8c\x01\n" +
	"\x13ExtendIdentityLease\x129.agynio.api.ziti_management.v1.ExtendIdentityLeaseRequest\x1a:.agynio.api.ziti_management.v1.ExtendIdentityLeaseResponseB\xa6\x02\n" +
	"!com.agynio.api.ziti_management.v1B\x13ZitiManagementProtoP\x01ZYgithub.com/agynio/ziti-management/.gen/go/agynio/api/ziti_management/v1;ziti_managementv1\xa2\x02\x03AAZ\xaa\x02\x1cAgynio.Api.ZitiManagement.V1\xca\x02\x1cAgynio\\Api\\ZitiManagement\\V1\xe2\x02(Agynio\\Api\\ZitiManagement\\V1\\GPBMetadata\xea\x02\x1fAgynio::Api::ZitiManagement::V1b\x06proto3"

var (
	file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescOnce sync.Once
	file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescData []byte
)

func file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP() []byte {
	file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescOnce.Do(func() {
		file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc), len(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc)))
	})
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescData
}

var file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_agynio_api_ziti_management_v1_ziti_management_proto_goTypes = []any{
	(ServiceType)(0),                       // 0: agynio.api.ziti_management.v1.ServiceType
	(*ManagedIdentity)(nil),                // 1: agynio.api.ziti_management.v1.ManagedIdentity
	(*CreateAgentIdentityRequest)(nil),     // 2: agynio.api.ziti_management.v1.CreateAgentIdentityRequest
	(*CreateAgentIdentityResponse)(nil),    // 3: agynio.api.ziti_management.v1.CreateAgentIdentityResponse
	(*CreateAppIdentityRequest)(nil),       // 4: agynio.api.ziti_management.v1.CreateAppIdentityRequest
	(*CreateAppIdentityResponse)(nil),      // 5: agynio.api.ziti_management.v1.CreateAppIdentityResponse
	(*DeleteAppIdentityRequest)(nil),       // 6: agynio.api.ziti_management.v1.DeleteAppIdentityRequest
	(*DeleteAppIdentityResponse)(nil),      // 7: agynio.api.ziti_management.v1.DeleteAppIdentityResponse
	(*DeleteIdentityRequest)(nil),          // 8: agynio.api.ziti_management.v1.DeleteIdentityRequest
	(*DeleteIdentityResponse)(nil),         // 9: agynio.api.ziti_management.v1.DeleteIdentityResponse
	(*ListManagedIdentitiesRequest)(nil),   // 10: agynio.api.ziti_management.v1.ListManagedIdentitiesRequest
	(*ListManagedIdentitiesResponse)(nil),  // 11: agynio.api.ziti_management.v1.ListManagedIdentitiesResponse
	(*ResolveIdentityRequest)(nil),         // 12: agynio.api.ziti_management.v1.ResolveIdentityRequest
	(*ResolveIdentityResponse)(nil),        // 13: agynio.api.ziti_management.v1.ResolveIdentityResponse
	(*RequestServiceIdentityRequest)(nil),  // 14: agynio.api.ziti_management.v1.RequestServiceIdentityRequest
	(*RequestServiceIdentityResponse)(nil), // 15: agynio.api.ziti_management.v1.RequestServiceIdentityResponse
	(*ExtendIdentityLeaseRequest)(nil),     // 16: agynio.api.ziti_management.v1.ExtendIdentityLeaseRequest
	(*ExtendIdentityLeaseResponse)(nil),    // 17: agynio.api.ziti_management.v1.ExtendIdentityLeaseResponse
	(v1.IdentityType)(0),                   // 18: agynio.api.identity.v1.IdentityType
	(*timestamppb.Timestamp)(nil),          // 19: google.protobuf.Timestamp
}
var file_agynio_api_ziti_management_v1_ziti_management_proto_depIdxs = []int32{
	18, // 0: agynio.api.ziti_management.v1.ManagedIdentity.identity_type:type_name -> agynio.api.identity.v1.IdentityType
	19, // 1: agynio.api.ziti_management.v1.ManagedIdentity.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: agynio.api.ziti_management.v1.ListManagedIdentitiesRequest.identity_type:type_name -> agynio.api.identity.v1.IdentityType
	1,  // 3: agynio.api.ziti_management.v1.ListManagedIdentitiesResponse.identities:type_name -> agynio.api.ziti_management.v1.ManagedIdentity
	18, // 4: agynio.api.ziti_management.v1.ResolveIdentityResponse.identity_type:type_name -> agynio.api.identity.v1.IdentityType
	0,  // 5: agynio.api.ziti_management.v1.RequestServiceIdentityRequest.service_type:type_name -> agynio.api.ziti_management.v1.ServiceType
	2,  // 6: agynio.api.ziti_management.v1.ZitiManagementService.CreateAgentIdentity:input_type -> agynio.api.ziti_management.v1.CreateAgentIdentityRequest
	4,  // 7: agynio.api.ziti_management.v1.ZitiManagementService.CreateAppIdentity:input_type -> agynio.api.ziti_management.v1.CreateAppIdentityRequest
	8,  // 8: agynio.api.ziti_management.v1.ZitiManagementService.DeleteIdentity:input_type -> agynio.api.ziti_management.v1.DeleteIdentityRequest
	6,  // 9: agynio.api.ziti_management.v1.ZitiManagementService.DeleteAppIdentity:input_type -> agynio.api.ziti_management.v1.DeleteAppIdentityRequest
	10, // 10: agynio.api.ziti_management.v1.ZitiManagementService.ListManagedIdentities:input_type -> agynio.api.ziti_management.v1.ListManagedIdentitiesRequest
	12, // 11: agynio.api.ziti_management.v1.ZitiManagementService.ResolveIdentity:input_type -> agynio.api.ziti_management.v1.ResolveIdentityRequest
	14, // 12: agynio.api.ziti_management.v1.ZitiManagementService.RequestServiceIdentity:input_type -> agynio.api.ziti_management.v1.RequestServiceIdentityRequest
	16, // 13: agynio.api.ziti_management.v1.ZitiManagementService.ExtendIdentityLease:input_type -> agynio.api.ziti_management.v1.ExtendIdentityLeaseRequest
	3,  // 14: agynio.api.ziti_management.v1.ZitiManagementService.CreateAgentIdentity:output_type -> agynio.api.ziti_management.v1.CreateAgentIdentityResponse
	5,  // 15: agynio.api.ziti_management.v1.ZitiManagementService.CreateAppIdentity:output_type -> agynio.api.ziti_management.v1.CreateAppIdentityResponse
	9,  // 16: agynio.api.ziti_management.v1.ZitiManagementService.DeleteIdentity:output_type -> agynio.api.ziti_management.v1.DeleteIdentityResponse
	7,  // 17: agynio.api.ziti_management.v1.ZitiManagementService.DeleteAppIdentity:output_type -> agynio.api.ziti_management.v1.DeleteAppIdentityResponse
	11, // 18: agynio.api.ziti_management.v1.ZitiManagementService.ListManagedIdentities:output_type -> agynio.api.ziti_management.v1.ListManagedIdentitiesResponse
	13, // 19: agynio.api.ziti_management.v1.ZitiManagementService.ResolveIdentity:output_type -> agynio.api.ziti_management.v1.ResolveIdentityResponse
	15, // 20: agynio.api.ziti_management.v1.ZitiManagementService.RequestServiceIdentity:output_type -> agynio.api.ziti_management.v1.RequestServiceIdentityResponse
	17, // 21: agynio.api.ziti_management.v1.ZitiManagementService.ExtendIdentityLease:output_type -> agynio.api.ziti_management.v1.ExtendIdentityLeaseResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agynio_api_ziti_management_v1_ziti_management_proto_init() }
func file_agynio_api_ziti_management_v1_ziti_management_proto_init() {
	if File_agynio_api_ziti_management_v1_ziti_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc), len(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_ziti_management_v1_ziti_management_proto_goTypes,
		DependencyIndexes: file_agynio_api_ziti_management_v1_ziti_management_proto_depIdxs,
		EnumInfos:         file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes,
		MessageInfos:      file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes,
	}.Build()
	File_agynio_api_ziti_management_v1_ziti_management_proto = out.File
	file_agynio_api_ziti_management_v1_ziti_management_proto_goTypes = nil
	file_agynio_api_ziti_management_v1_ziti_management_proto_depIdxs = nil
}
